/* eslint-disable no-multi-spaces */

// Application
export const APP_BOOTUP = 'APP_BOOTUP';

// Authentication
export const SIGNIN_USER_REQUEST = 'SIGNIN_USER_REQUEST';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNIN_USER_ERROR   = 'SIGNIN_USER_ERROR';

export const CLEAR_SIGNIN_ERROR  = 'CLEAR_SIGNIN_ERROR';

export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_ERROR   = 'SIGNUP_USER_ERROR';

export const CLEAR_SIGNUP_ERROR  = 'CLEAR_SIGNUP_ERROR';

export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';

export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_ERROR   = 'REFRESH_TOKEN_ERROR';

export const AUTHENTICATE_FROM_TOKEN = 'AUTHENTICATE_FROM_TOKEN';

// Presence
export const DISPATCH_PRESENCE_STATE = 'DISPATCH_PRESENCE_STATE';
export const DISPATCH_PRESENCE_DIFF  = 'DISPATCH_PRESENCE_DIFF';

// Socket
export const OPEN_SOCKET         = 'OPEN_SOCKET';
export const CLOSE_SOCKET        = 'CLOSE_SOCKET';
export const SOCKET_CONNECTED    = 'SOCKET_CONNECTED';
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED';
export const SOCKET_ERROR        = 'SOCKET_ERROR';
export const SOCKET_CLOSED       = 'SOCKET_CLOSED';

// Channels
export const JOIN_CHANNEL          = 'JOIN_CHANNEL';
export const LEAVE_CHANNEL         = 'LEAVE_CHANNEL';
export const CHANNEL_CONNECTED     = 'CHANNEL_CONNECTED';
export const CHANNEL_DISCONNECTED  = 'CHANNEL_DISCONNECTED';
export const CHANNEL_ERROR         = 'CHANNEL_ERROR';
export const CHANNEL_CLOSED        = 'CHANNEL_CLOSED';
export const SEND_COMMAND          = 'SEND_COMMAND';
export const CONNECT_CHANNEL_ERROR = 'CONNECT_CHANNEL_ERROR';

// Requests
export const REQUESTS_RECEIVED = 'REQUESTS_RECEIVED';
export const REQUEST_CREATED   = 'REQUEST_CREATED';
export const REQUEST_CANCELLED = 'REQUEST_CANCELLED';
export const REQUEST_ACCEPTED  = 'REQUEST_ACCEPTED';

export const REQUEST_CREATED_ERROR   = 'REQUEST_CREATED_ERROR';
export const REQUEST_CANCELLED_ERROR = 'REQUEST_CANCELLED_ERROR';
export const REQUEST_ACCEPTED_ERROR  = 'REQUEST_ACCEPTED_ERROR';

// Games & GameInfo
export const GAMES_RECEIVED   = 'GAMES_RECEIVED';
export const GAME_ADDED       = 'GAME_ADDED';
export const GAME_REMOVED     = 'GAME_REMOVED';
export const GAME_FORCE_QUIT  = 'GAME_FORCE_QUIT';
export const JOIN_GAME        = 'JOIN_GAME';
export const UPDATE_GAME_INFO = 'UPDATE_GAME_INFO';

// GameState
export const UPDATE_GAME_STATE = 'UPDATE_GAME_STATE';
export const PLAY_MOVE_ERROR   = 'PLAY_MOVE_ERROR';
export const PASS_ERROR        = 'PASS_ERROR';
export const RESIGN_ERROR      = 'RESIGN_ERROR';

//  Chat
export const MESSAGE_CREATED         = 'MESSAGE_CREATED';
export const MESSAGES_RECEIVED       = 'MESSAGES_RECEIVED';
export const MESSAGE_CREATED_ERROR   = 'MESSAGE_CREATED_ERROR';
export const MESSAGES_RECEIVED_ERROR = 'MESSAGES_RECEIVED_ERROR';

/* eslint-enable no-multi-spaces */